<?php
$_['gopay_setting'] = array(
	'currencies' => array(
		'CZK'  => 'Czech koruna',
		'EUR'  => 'Euro',
		'PLN'  => 'Polish złoty',
		'USD'  => 'United States dollar',
		'GBP'  => 'Pound sterling',
		'HUF'  => 'Hungarian forint',
		'RON'  => 'Romanian lei',
		'BGN'  => 'Bulgarian lev',
		'HRK'  => 'Croatian kuna',
	),
	'payment_methods' => array(
		'PAYMENT_CARD' => array( 'label' => 'Payment card' ),
		'BANK_ACCOUNT' => array( 'label' => 'Bank account' ),
		'GPAY'         => array( 'label' => 'Google Pay' ),
		'APPLE_PAY'    => array( 'label' => 'Apple Pay' ),
		'GOPAY'        => array( 'label' => 'GoPay wallet' ),
		'PAYPAL'       => array( 'label' => 'PayPal wallet' ),
		'MPAYMENT'     => array( 'label' => 'mPlatba (mobile payment)' ),
		'PRSMS'        => array( 'label' => 'Premium SMS' ),
		'PAYSAFECARD'  => array( 'label' => 'PaySafeCard coupon' ),
		'BITCOIN'      => array( 'label' => 'Bitcoin wallet' ),
		'CLICK_TO_PAY' => array( 'label' => 'Click to Pay' ),
	),
	'banks' => array(
		'GIBACZPX'     => array( 'label' => 'Česká Spořitelna', 'country' => 'CZ' ),
		'KOMBCZPP'     => array( 'label' => 'Komerční Banka', 'country' => 'CZ' ),
		'RZBCCZPP'     => array( 'label' => 'Raiffeisenbank', 'country' => 'CZ' ),
		'FIOBCZPP'     => array( 'label' => 'FIO Banka', 'country' => 'CZ' ),
		'BACXCZPP'     => array( 'label' => 'UniCredit Bank', 'country' => 'CZ' ),
		'BREXCZPP'     => array( 'label' => 'mBank', 'country' => 'CZ' ),
		'CEKOCZPP'     => array( 'label' => 'ČSOB', 'country' => 'CZ' ),
		'CEKOCZPP-ERA' => array( 'label' => 'Poštovní Spořitelna', 'country' => 'CZ' ),
		'AGBACZPP'     => array( 'label' => 'Moneta Money Bank', 'country' => 'CZ' ),
		'AIRACZPP'     => array( 'label' => 'AirBank', 'country' => 'CZ' ),
		'EQBKCZPP'     => array( 'label' => 'EQUA Bank', 'country' => 'CZ' ),
		'INGBCZPP'     => array( 'label' => 'ING Bank', 'country' => 'CZ' ),
		'EXPNCZPP'     => array( 'label' => 'Expobank', 'country' => 'CZ' ),
		'OBKLCZ2X'     => array( 'label' => 'OberBank AG', 'country' => 'CZ' ),
		'SUBACZPP'     => array( 'label' => 'Všeobecná Úvěrová Banka', 'country' => 'CZ' ),
		'TATRSKBX'     => array( 'label' => 'Tatra Banka', 'country' => 'SK' ),
		'SUBASKBX'     => array( 'label' => 'Všeobecná Úverová Banka', 'country' => 'SK' ),
		'UNCRSKBX'     => array( 'label' => 'UniCredit Bank', 'country' => 'SK' ),
		'GIBASKBX'     => array( 'label' => 'Slovenská Sporiteľňa', 'country' => 'SK' ),
		'POBNSKBA'     => array( 'label' => 'Poštová Banka', 'country' => 'SK' ),
		'OTPVSKBX'     => array( 'label' => 'OTP Banka', 'country' => 'SK' ),
		'KOMASK2X'     => array( 'label' => 'Prima Banka', 'country' => 'SK' ),
		'CITISKBA'     => array( 'label' => 'Citibank Europe', 'country' => 'SK' ),
		'FIOZSKBA'     => array( 'label' => 'FIO Banka', 'country' => 'SK' ),
		'INGBSKBX'     => array( 'label' => 'ING Wholesale Banking', 'country' => 'SK' ),
		'BREXSKBX'     => array( 'label' => 'mBank', 'country' => 'SK' ),
		'JTBPSKBA'     => array( 'label' => 'J&T Banka', 'country' => 'SK' ),
		'OBKLSKBA'     => array( 'label' => 'OberBank AG', 'country' => 'SK' ),
		'BSLOSK22'     => array( 'label' => 'Privatbanka', 'country' => 'SK' ),
		'BFKKSKBB'     => array( 'label' => 'BKS Bank AG', 'country' => 'SK' ),
		'GBGCPLPK'     => array( 'label' => 'Getin Bank', 'country' => 'PL' ),
		'NESBPLPW'     => array( 'label' => 'Nest Bank', 'country' => 'PL' ),
		'VOWAPLP9'     => array( 'label' => 'Volkswagen Bank', 'country' => 'PL' ),
		'CITIPLPX'     => array( 'label' => 'Citi handlowy', 'country' => 'PL' ),
		'WBKPPLPP'     => array( 'label' => 'Santander', 'country' => 'PL' ),
		'BIGBPLPW'     => array( 'label' => 'Millenium Bank', 'country' => 'PL' ),
		'EBOSPLPW'     => array( 'label' => 'Bank Ochrony Srodowiska', 'country' => 'PL' ),
		'PKOPPLPW'     => array( 'label' => 'Pekao Bank', 'country' => 'PL' ),
		'PPABPLPK'     => array( 'label' => 'BNP Paribas', 'country' => 'PL' ),
		'BPKOPLPW'     => array( 'label' => 'Owszechna Kasa Oszczednosci Bank Polsk', 'country' => 'PL' ),
		'AGRIPLPR'     => array( 'label' => 'Credit Agricole Banka Polska', 'country' => 'PL' ),
		'GBGCPLPK-NOB' => array( 'label' => 'Noble Bank', 'country' => 'PL' ),
		'POLUPLPR'     => array( 'label' => 'BPS/Bank Nowy BFG', 'country' => 'PL' ),
		'BREXPLPW'     => array( 'label' => 'mBank', 'country' => 'PL' ),
		'INGBPLPW'     => array( 'label' => 'ING Bank', 'country' => 'PL' ),
		'ALBPPLPW'     => array( 'label' => 'Alior', 'country' => 'PL' ),
		'IEEAPLPA'     => array( 'label' => 'IdeaBank', 'country' => 'PL' ),
		'POCZPLP4'     => array( 'label' => 'Pocztowy24', 'country' => 'PL' ),
		'IVSEPLPP'     => array( 'label' => 'Plus Bank', 'country' => 'PL' ),
		'TOBAPLPW'     => array( 'label' => 'Toyota Bank', 'country' => 'PL' ),
		'OTHERS'       => array( 'label' => 'Another bank', 'country' => '' ),
	),
	'country_to_language' => array(
		'AD' => 'CA',
		'AE' => 'AR',
		'AF' => 'FA',
		'AG' => 'EN',
		'AI' => 'EN',
		'AL' => 'SQ',
		'AM' => 'HY',
		'AO' => 'PT',
		'AR' => 'ES',
		'AS' => 'EN',
		'AT' => 'DE',
		'AU' => 'EN',
		'AW' => 'NL',
		'AX' => 'SV',
		'AZ' => 'AZ',
		'BA' => 'BS',
		'BB' => 'EN',
		'BD' => 'BN',
		'BE' => 'NL',
		'BF' => 'FR',
		'BG' => 'BG',
		'BH' => 'AR',
		'BI' => 'FR',
		'BJ' => 'FR',
		'BL' => 'FR',
		'BM' => 'EN',
		'BN' => 'MS',
		'BO' => 'ES',
		'BQ' => 'NL',
		'BR' => 'PT',
		'BS' => 'EN',
		'BT' => 'DZ',
		'BW' => 'EN',
		'BY' => 'BE',
		'BZ' => 'EN',
		'CA' => 'EN',
		'CC' => 'MS',
		'CD' => 'FR',
		'CF' => 'FR',
		'CG' => 'FR',
		'CH' => 'DE',
		'CI' => 'FR',
		'CK' => 'EN',
		'CL' => 'ES',
		'CM' => 'EN',
		'CN' => 'ZH',
		'CO' => 'ES',
		'CR' => 'ES',
		'CU' => 'ES',
		'CV' => 'PT',
		'CW' => 'NL',
		'CX' => 'EN',
		'CY' => 'EL',
		'CZ' => 'CS',
		'DE' => 'DE',
		'DJ' => 'FR',
		'DK' => 'DA',
		'DM' => 'EN',
		'DO' => 'ES',
		'DZ' => 'AR',
		'EC' => 'ES',
		'EE' => 'ET',
		'EG' => 'AR',
		'EH' => 'AR',
		'ER' => 'AA',
		'ES' => 'ES',
		'ET' => 'AM',
		'FI' => 'FI',
		'FJ' => 'EN',
		'FK' => 'EN',
		'FM' => 'EN',
		'FO' => 'FO',
		'FR' => 'FR',
		'GA' => 'FR',
		'GB' => 'EN',
		'GD' => 'EN',
		'GE' => 'KA',
		'GF' => 'FR',
		'GG' => 'EN',
		'GH' => 'EN',
		'GI' => 'EN',
		'GL' => 'KL',
		'GM' => 'EN',
		'GN' => 'FR',
		'GP' => 'FR',
		'GQ' => 'ES',
		'GR' => 'EL',
		'GS' => 'EN',
		'GT' => 'ES',
		'GU' => 'EN',
		'GW' => 'PT',
		'GY' => 'EN',
		'HK' => 'ZH',
		'HN' => 'ES',
		'HR' => 'HR',
		'HT' => 'HT',
		'HU' => 'HU',
		'ID' => 'ID',
		'IE' => 'EN',
		'IL' => 'HE',
		'IM' => 'EN',
		'IN' => 'EN',
		'IO' => 'EN',
		'IQ' => 'AR',
		'IR' => 'FA',
		'IS' => 'IS',
		'IT' => 'IT',
		'JE' => 'EN',
		'JM' => 'EN',
		'JO' => 'AR',
		'JP' => 'JA',
		'KE' => 'EN',
		'KG' => 'KY',
		'KH' => 'KM',
		'KI' => 'EN',
		'KM' => 'AR',
		'KN' => 'EN',
		'KP' => 'KO',
		'KR' => 'KO',
		'XK' => 'SQ',
		'KW' => 'AR',
		'KY' => 'EN',
		'KZ' => 'KK',
		'LA' => 'LO',
		'LB' => 'AR',
		'LC' => 'EN',
		'LI' => 'DE',
		'LK' => 'SI',
		'LR' => 'EN',
		'LS' => 'EN',
		'LT' => 'LT',
		'LU' => 'LB',
		'LV' => 'LV',
		'LY' => 'AR',
		'MA' => 'AR',
		'MC' => 'FR',
		'MD' => 'RO',
		'ME' => 'SR',
		'MF' => 'FR',
		'MG' => 'FR',
		'MH' => 'MH',
		'MK' => 'MK',
		'ML' => 'FR',
		'MM' => 'MY',
		'MN' => 'MN',
		'MO' => 'ZH',
		'MP' => 'FIL',
		'MQ' => 'FR',
		'MR' => 'AR',
		'MS' => 'EN',
		'MT' => 'MT',
		'MU' => 'EN',
		'MV' => 'DV',
		'MW' => 'NY',
		'MX' => 'ES',
		'MY' => 'MS',
		'MZ' => 'PT',
		'NA' => 'EN',
		'NC' => 'FR',
		'NE' => 'FR',
		'NF' => 'EN',
		'NG' => 'EN',
		'NI' => 'ES',
		'NL' => 'NL',
		'NO' => 'NO',
		'NP' => 'NE',
		'NR' => 'NA',
		'NU' => 'NIU',
		'NZ' => 'EN',
		'OM' => 'AR',
		'PA' => 'ES',
		'PE' => 'ES',
		'PF' => 'FR',
		'PG' => 'EN',
		'PH' => 'TL',
		'PK' => 'UR',
		'PL' => 'PL',
		'PM' => 'FR',
		'PN' => 'EN',
		'PR' => 'EN',
		'PS' => 'AR',
		'PT' => 'PT',
		'PW' => 'PAU',
		'PY' => 'ES',
		'QA' => 'AR',
		'RE' => 'FR',
		'RO' => 'RO',
		'RS' => 'SR',
		'RU' => 'RU',
		'RW' => 'RW',
		'SA' => 'AR',
		'SB' => 'EN',
		'SC' => 'EN',
		'SD' => 'AR',
		'SS' => 'EN',
		'SE' => 'SV',
		'SG' => 'CMN',
		'SH' => 'EN',
		'SI' => 'SL',
		'SJ' => 'NO',
		'SK' => 'SK',
		'SL' => 'EN',
		'SM' => 'IT',
		'SN' => 'FR',
		'SO' => 'SO',
		'SR' => 'NL',
		'ST' => 'PT',
		'SV' => 'ES',
		'SX' => 'NL',
		'SY' => 'AR',
		'SZ' => 'EN',
		'TC' => 'EN',
		'TD' => 'FR',
		'TF' => 'FR',
		'TG' => 'FR',
		'TH' => 'TH',
		'TJ' => 'TG',
		'TK' => 'TKL',
		'TL' => 'TET',
		'TM' => 'TK',
		'TN' => 'AR',
		'TO' => 'TO',
		'TR' => 'TR',
		'TT' => 'EN',
		'TV' => 'TVL',
		'TW' => 'ZH',
		'TZ' => 'SW',
		'UA' => 'UK',
		'UG' => 'EN',
		'UM' => 'EN',
		'US' => 'EN',
		'UY' => 'ES',
		'UZ' => 'UZ',
		'VA' => 'LA',
		'VC' => 'EN',
		'VE' => 'ES',
		'VG' => 'EN',
		'VI' => 'EN',
		'VN' => 'VI',
		'VU' => 'BI',
		'WF' => 'WLS',
		'WS' => 'SM',
		'YE' => 'AR',
		'YT' => 'FR',
		'ZA' => 'ZU',
		'ZM' => 'EN',
		'ZW' => 'EN',
		'CS' => 'CU',
		'AN' => 'NL',
	),
	'languages' => array(
		'CS' => 'Czech',
		'SK' => 'Slovak',
		'EN' => 'English',
		'DE' => 'German',
		'RU' => 'Russian',
		'PL' => 'Polish',
		'HU' => 'Hungarian',
		'RO' => 'Romanian',
		'BG' => 'Bulgarian',
		'HR' => 'Croatian',
		'IT' => 'Italian',
		'FR' => 'French',
		'ES' => 'Spanish',
		'UK' => 'Ukrainian',
	)
);