<?php
$_['gopay_setting'] = array(
	'currencies' => array(
		'CZK'  => 'Czech koruna',
		'EUR'  => 'Euro',
		'PLN'  => 'Polish złoty',
		'USD'  => 'United States dollar',
		'GBP'  => 'Pound sterling',
		'HUF'  => 'Hungarian forint',
		'RON'  => 'Romanian lei',
		'BGN'  => 'Bulgarian lev',
		'HRK'  => 'Croatian kuna',
	),
	'payment_methods' => array(
		'PAYMENT_CARD' => array( 'label' => 'Payment card' ),
		'BANK_ACCOUNT' => array( 'label' => 'Bank account' ),
		'GPAY'         => array( 'label' => 'Google Pay' ),
		'APPLE_PAY'    => array( 'label' => 'Apple Pay' ),
		'GOPAY'        => array( 'label' => 'GoPay wallet' ),
		'PAYPAL'       => array( 'label' => 'PayPal wallet' ),
		'MPAYMENT'     => array( 'label' => 'mPlatba (mobile payment)' ),
		'PRSMS'        => array( 'label' => 'Premium SMS' ),
		'PAYSAFECARD'  => array( 'label' => 'PaySafeCard coupon' ),
		'BITCOIN'      => array( 'label' => 'Bitcoin wallet' ),
		'CLICK_TO_PAY' => array( 'label' => 'Click to Pay' ),
	),
	'banks' => array(
		'GIBACZPX'     => array( 'label' => 'Česká Spořitelna', 'country' => 'CZ' ),
		'KOMBCZPP'     => array( 'label' => 'Komerční Banka', 'country' => 'CZ' ),
		'RZBCCZPP'     => array( 'label' => 'Raiffeisenbank', 'country' => 'CZ' ),
		'FIOBCZPP'     => array( 'label' => 'FIO Banka', 'country' => 'CZ' ),
		'BACXCZPP'     => array( 'label' => 'UniCredit Bank', 'country' => 'CZ' ),
		'BREXCZPP'     => array( 'label' => 'mBank', 'country' => 'CZ' ),
		'CEKOCZPP'     => array( 'label' => 'ČSOB', 'country' => 'CZ' ),
		'CEKOCZPP-ERA' => array( 'label' => 'Poštovní Spořitelna', 'country' => 'CZ' ),
		'AGBACZPP'     => array( 'label' => 'Moneta Money Bank', 'country' => 'CZ' ),
		'AIRACZPP'     => array( 'label' => 'AirBank', 'country' => 'CZ' ),
		'EQBKCZPP'     => array( 'label' => 'EQUA Bank', 'country' => 'CZ' ),
		'INGBCZPP'     => array( 'label' => 'ING Bank', 'country' => 'CZ' ),
		'EXPNCZPP'     => array( 'label' => 'Expobank', 'country' => 'CZ' ),
		'OBKLCZ2X'     => array( 'label' => 'OberBank AG', 'country' => 'CZ' ),
		'SUBACZPP'     => array( 'label' => 'Všeobecná Úvěrová Banka', 'country' => 'CZ' ),
		'TATRSKBX'     => array( 'label' => 'Tatra Banka', 'country' => 'SK' ),
		'SUBASKBX'     => array( 'label' => 'Všeobecná Úverová Banka', 'country' => 'SK' ),
		'UNCRSKBX'     => array( 'label' => 'UniCredit Bank', 'country' => 'SK' ),
		'GIBASKBX'     => array( 'label' => 'Slovenská Sporiteľňa', 'country' => 'SK' ),
		'POBNSKBA'     => array( 'label' => 'Poštová Banka', 'country' => 'SK' ),
		'OTPVSKBX'     => array( 'label' => 'OTP Banka', 'country' => 'SK' ),
		'KOMASK2X'     => array( 'label' => 'Prima Banka', 'country' => 'SK' ),
		'CITISKBA'     => array( 'label' => 'Citibank Europe', 'country' => 'SK' ),
		'FIOZSKBA'     => array( 'label' => 'FIO Banka', 'country' => 'SK' ),
		'INGBSKBX'     => array( 'label' => 'ING Wholesale Banking', 'country' => 'SK' ),
		'BREXSKBX'     => array( 'label' => 'mBank', 'country' => 'SK' ),
		'JTBPSKBA'     => array( 'label' => 'J&T Banka', 'country' => 'SK' ),
		'OBKLSKBA'     => array( 'label' => 'OberBank AG', 'country' => 'SK' ),
		'BSLOSK22'     => array( 'label' => 'Privatbanka', 'country' => 'SK' ),
		'BFKKSKBB'     => array( 'label' => 'BKS Bank AG', 'country' => 'SK' ),
		'GBGCPLPK'     => array( 'label' => 'Getin Bank', 'country' => 'PL' ),
		'NESBPLPW'     => array( 'label' => 'Nest Bank', 'country' => 'PL' ),
		'VOWAPLP9'     => array( 'label' => 'Volkswagen Bank', 'country' => 'PL' ),
		'CITIPLPX'     => array( 'label' => 'Citi handlowy', 'country' => 'PL' ),
		'WBKPPLPP'     => array( 'label' => 'Santander', 'country' => 'PL' ),
		'BIGBPLPW'     => array( 'label' => 'Millenium Bank', 'country' => 'PL' ),
		'EBOSPLPW'     => array( 'label' => 'Bank Ochrony Srodowiska', 'country' => 'PL' ),
		'PKOPPLPW'     => array( 'label' => 'Pekao Bank', 'country' => 'PL' ),
		'PPABPLPK'     => array( 'label' => 'BNP Paribas', 'country' => 'PL' ),
		'BPKOPLPW'     => array( 'label' => 'Owszechna Kasa Oszczednosci Bank Polsk', 'country' => 'PL' ),
		'AGRIPLPR'     => array( 'label' => 'Credit Agricole Banka Polska', 'country' => 'PL' ),
		'GBGCPLPK-NOB' => array( 'label' => 'Noble Bank', 'country' => 'PL' ),
		'POLUPLPR'     => array( 'label' => 'BPS/Bank Nowy BFG', 'country' => 'PL' ),
		'BREXPLPW'     => array( 'label' => 'mBank', 'country' => 'PL' ),
		'INGBPLPW'     => array( 'label' => 'ING Bank', 'country' => 'PL' ),
		'ALBPPLPW'     => array( 'label' => 'Alior', 'country' => 'PL' ),
		'IEEAPLPA'     => array( 'label' => 'IdeaBank', 'country' => 'PL' ),
		'POCZPLP4'     => array( 'label' => 'Pocztowy24', 'country' => 'PL' ),
		'IVSEPLPP'     => array( 'label' => 'Plus Bank', 'country' => 'PL' ),
		'TOBAPLPW'     => array( 'label' => 'Toyota Bank', 'country' => 'PL' ),
		'OTHERS'       => array( 'label' => 'Another bank', 'country' => '' ),
	),
);